
name: Compilar y desplegar
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Compilación
        run: |
          npm ci
          npm i -g @angular/cli
          ng build --configuration production --base-href "https://kyostenas.github.io/laboratory/"

      - name: Desplegado
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/laboratory/browser
        env:
          BRANCH: gh-pages

      
